before_script:
  - echo $CI_PROJECT_DIR
  - docker --version
  - docker-compose --version

stages:
  - unittest
  - build
  - citests

build_main:
  stage: build
  tags:
    - docker
  script:
    - docker/run_docker.sh -b

unittest:
  stage: unittest
  tags:
    - docker
  script:
    - docker/run_docker.sh -t

citests:
  stage: citests
  tags:
    - docker
  script:
    - docker/run_docker.sh --clean
    - docker/run_docker.sh --ci-tests
    - docker/run_docker.sh --clean
